app ansible-host=192.168.1.105  ansible-connection=ssh  ansible-user=vlad ansible-ssh-pass=q1w2e3
app ansible-host=192.168.1.106  ansible-connection=ssh  ansible-user=machine3 ansible-ssh-pass=q1w2e3
ansible-host=localhost  ansible-connection=local ansible-user=bban ansible_password=q1w2e3



[load_balanser]
192.168.1.105

[fastapp]
192.168.1.106

[all]:children
