- name: Install containerd
  hosts: node1
  become: true
  tasks:
    - name: Install
      ansible.builtin.script:
        cmd: ../../bash/install_and_check_containerD.sh
      register: installer
    - name: Debug containerd installer
      ansible.builtin.debug:
        msg: " debug installer {{ installer.stdout }}"
#   hosts: node1
#   become: true
#   tasks:
#     - name: Remove
#       ansible.builtin.script:
#         cmd: ../../bash/remove_containerD.sh
#     - name: Remove_daemon_reload
#       ansible.builtin.systemd_service:
#         daemon_reload: true
#     - name: Remove_check
#       ansible.builtin.service_facts:
#     - name: Debug service state
#       ansible.builtin.debug:
#         var: ansible_facts.services['containerd.service'].state
#     - name: Reboot
#       ansible.builtin.command:
#         cmd: shutdown -r -t 10
#       register: reboot_var
#       changed_when: reboot_var.rc != 0status {{ status.stdout }}"
- name: Preparation for installer modules kubernetes
  hosts: node1
  become: true
  tasks:
    - name: Settings validation packets
      ansible.builtin.script:
        cmd: ../../bash/Setting_vaidity_packet_ipv4.sh
      register: validation_pack
      changed_when: validation_pack != 0
